FROM python:alpine

WORKDIR /django

RUN apk update && \
    apk upgrade && \
	apk add postgresql-client curl npm

COPY . .

RUN pip install -r ./requirements.txt

RUN npm install jwt-decode

RUN chmod +x ./entrypoint.sh

ENTRYPOINT [ "/bin/sh", "./entrypoint.sh" ]