services:

  postgresql:
    container_name: postgresql
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - ./src/postgresql/data:/var/lib/postgresql/data
    networks:
      - django_postgresql

  django:
    container_name: django
    build:
      context: ./src/django
    env_file:
      - .env
    volumes:
        - ./src/django:/django
    depends_on:
      - postgresql
    networks:
      - django_postgresql
      - django_nginx

  nginx:
    container_name: nginx
    image: owasp/modsecurity-crs:nginx-alpine
    volumes:
      - ./src/nginx/certs:/etc/nginx/conf
      - ./src/nginx/conf/default.conf:/etc/nginx/templates/conf.d/default.conf.template
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - django_nginx

networks:
  django_postgresql:
  django_nginx: